#spring.application.name=shoppingMall

server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mydatabase.clkwweaguf6x.ap-northeast-2.rds.amazonaws.com:3306/mydatabase
    username: woo
    password: 84547909a!
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        #show_sql: true   -> systemout? ??? ??? ???? ?? ?? ??

logging:
  level:
    org.hibernate.SQL : debug
    org.hibernate.type: trace     #????? ??? ????.
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.boot.autoconfigure.security: INFO

decorator:
  datasource:
    p6spy:
      enable-logging: true

append: com.p6spy.engine.spy.appender.Slf4JLogger








